version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8021:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logger
      - POSTGRES_IPADDR=db
      - FLAG=YetiCTF{aDM1n_LUB17_P1v0}
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logger
